### ISSUE TITLE
vsync with bluetooth

### ISSUE THREAD

**Issue by fega** [ernestum/VSync#1]
hello! 
im wondering if I could use your library with a bluetooth adapter.

thak you.

**Comment by ernestum** [comment]
That depends on the kind of bluethooth adapter you use I guess. I have never used one and I do not own one so I can not test it. If it is one of those adapters, that basically just act as a serial bridge and open a serial device, it should just be a matter of using the right file descriptor when setting up the serial connection.

If you send me a link to the bluetooth adapter you want to use I could have a quick look at it.

**Comment by fega** [comment]
bluetooth HC-05 as the main option: http://www.amazon.com/Innogear-Wireless-Bluetooth-Transceiver-Arduino/dp/B00JP05S6C

for other side: the library function with android via cable? thankyou :)

**Comment by ernestum** [comment]
What? That thing is close to 2000 bucks?! I guess you could find something less expensive. '

You can make it work though, because as far as I understand it is indeed a serial bridge. You still need to modify the code to do the bluetooth handshake (passcode? I have no experience there) so do not expect the provided examples to work out of the box.

As for android: I do not know but probably not. There are two things that you need to check:
1. Your android device needs an USB host controller so it accepts slaves such as the Arduino
2. The VSync for Processing depends on the Serial library by Processing which again depends on the rxtx library for java. You need to make sure, that all this runs on your android device properly.
